# Perfil DEV (H2 en memoria)
spring:
  profiles: dev
  
  datasource:
    url: jdbc:h2:mem:employeedb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: update # H2 puede crear el esquema autom√°ticamente
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true # Habilita la consola H2 en /h2-console
      path: /h2-console